### ISSUE TITLE
Crashes on search

### ISSUE THREAD

**Issue by stillenacht288** [seanfhear/tab-scraper#13]
Downloaded the executable. Opens up, and once I input text and hit "search," it crashes. Running Windows 10.

**Comment by fstanley** [comment]
Same

**Comment by yonderbread** [comment]
Seems that some data that's supposed to be in json format is no longer being scraped correctly ending up in a `JSONDecodeError`. I'm going to fork this project and see if I can fix it.

**Comment by mrbooshehri** [comment]
It also crashes on Linux

the error :

`Traceback (most recent call last):

  File "tab_scraper.py", line 159, in search_tabs
  File "utils.py", line 33, in search_tabs
  File "json/__init__.py", line 348, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
zsh: abort (core dumped)  ./tab_scraper`

**Comment by BernhardSigl** [comment]
Same on Win11
